### ISSUE TITLE
Amostras e gráfico não estão aparecendo na página de armadilhas

### ISSUE THREAD

**Issue by odascatolini** [aetrapp/aetrapp-dashboard#55]
@vgeorge @miguelpeixe 

Em todas as páginas de armadilha que tem amostras, não vemos os gráficos nem as amostras, somente a mensagem "Não há registro de amostras para esta armadilha".

**Comment by vgeorge** [comment]
Resolvido, alguns armadilhas tinham a propriedade "sampleCount" vazia e não havia verificação pela interface, fazendo com que nada aparecesse. Atualizei o banco e coloquei o valor 0 como padrão para o "sampleCount".

**Comment by odascatolini** [comment]
ok @vgeorge
